require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OrderHistoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OrderHistory. As you add validations to OrderHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all order_histories as @order_histories" do
      order_history = OrderHistory.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:order_histories)).to eq([order_history])
    end
  end

  describe "GET #show" do
    it "assigns the requested order_history as @order_history" do
      order_history = OrderHistory.create! valid_attributes
      get :show, {:id => order_history.to_param}, valid_session
      expect(assigns(:order_history)).to eq(order_history)
    end
  end

  describe "GET #new" do
    it "assigns a new order_history as @order_history" do
      get :new, {}, valid_session
      expect(assigns(:order_history)).to be_a_new(OrderHistory)
    end
  end

  describe "GET #edit" do
    it "assigns the requested order_history as @order_history" do
      order_history = OrderHistory.create! valid_attributes
      get :edit, {:id => order_history.to_param}, valid_session
      expect(assigns(:order_history)).to eq(order_history)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OrderHistory" do
        expect {
          post :create, {:order_history => valid_attributes}, valid_session
        }.to change(OrderHistory, :count).by(1)
      end

      it "assigns a newly created order_history as @order_history" do
        post :create, {:order_history => valid_attributes}, valid_session
        expect(assigns(:order_history)).to be_a(OrderHistory)
        expect(assigns(:order_history)).to be_persisted
      end

      it "redirects to the created order_history" do
        post :create, {:order_history => valid_attributes}, valid_session
        expect(response).to redirect_to(OrderHistory.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved order_history as @order_history" do
        post :create, {:order_history => invalid_attributes}, valid_session
        expect(assigns(:order_history)).to be_a_new(OrderHistory)
      end

      it "re-renders the 'new' template" do
        post :create, {:order_history => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested order_history" do
        order_history = OrderHistory.create! valid_attributes
        put :update, {:id => order_history.to_param, :order_history => new_attributes}, valid_session
        order_history.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested order_history as @order_history" do
        order_history = OrderHistory.create! valid_attributes
        put :update, {:id => order_history.to_param, :order_history => valid_attributes}, valid_session
        expect(assigns(:order_history)).to eq(order_history)
      end

      it "redirects to the order_history" do
        order_history = OrderHistory.create! valid_attributes
        put :update, {:id => order_history.to_param, :order_history => valid_attributes}, valid_session
        expect(response).to redirect_to(order_history)
      end
    end

    context "with invalid params" do
      it "assigns the order_history as @order_history" do
        order_history = OrderHistory.create! valid_attributes
        put :update, {:id => order_history.to_param, :order_history => invalid_attributes}, valid_session
        expect(assigns(:order_history)).to eq(order_history)
      end

      it "re-renders the 'edit' template" do
        order_history = OrderHistory.create! valid_attributes
        put :update, {:id => order_history.to_param, :order_history => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested order_history" do
      order_history = OrderHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => order_history.to_param}, valid_session
      }.to change(OrderHistory, :count).by(-1)
    end

    it "redirects to the order_histories list" do
      order_history = OrderHistory.create! valid_attributes
      delete :destroy, {:id => order_history.to_param}, valid_session
      expect(response).to redirect_to(order_histories_url)
    end
  end

end
